[package]
name = "cas_offinder_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencl3 = "0.3.0"
crossbeam-channel = "0.5"
